#import './fragments/ProductAttachmentsSetFragment.gql'
mutation updateProductAttachmentsSet ($input: ProductAttachmentsSetInput!) {
  updateProductAttachmentsSet(input: $input){
    ... ProductAttachmentsSetData
  }
}
