#import './fragments/PVItemFragment.gql'
mutation updateProductVariations ($parentId: ID!, $inputArr: [PVItemInput!]!) {
  updateProductVariations(parentId: $parentId, inputArr: $inputArr){
    ... PVItemData
  }
}
