#import './../../product/fragments/ProductBasicFragment.gql'
#import './../../product/fragments/ProductPriceFragment.gql'
#import "./../../product/fragments/ProductVariableFeaturesFragment.gql"
#import "./../../product/fragments/ProductVariationItemFragment.gql"
fragment LinkedProductsData on ProductLinks {
  id
  links{
    product{
    ... ProductBasicData
    ... ProductPriceData

      ... on VariableProduct {

        variableFeatures{
          ... ProductVariableFeatureData
        }

        variations{
          id
          sku
          price
          regularPrice
          volumePrice
          regularVolumePrice
          saleIsActive
          featuresConfig
        }
      }

    }
    variationsSku
  }
}
