query getPaginatedCategoriesMeta ($args: JSON) {
    getPaginatedCategoriesMeta(args: $args){
      total
      items {
        id
        createdAt
        updatedAt
        name
        slug
      }
    }
 }
