#import "./fragments/LinkedProductsFragment.gql"
query linkedProducts ($field: String!, $value: String!, $linkType: String!) {
  linkedProducts(field: $field, value: $value, linkType: $linkType){
    ... LinkedProductsData
  }
}
