#import './fragments/VariableFeatureSetFragment.gql'
mutation createVariableFeatureSet ($input: VariableFeatureSetInput!) {
  createVariableFeatureSet(input: $input){
    ... VariableFeatureSetData
  }
}
