#import './fragments/VariableFeatureSetFragment.gql'
mutation updateVariableFeatureSet ($id: ID!, $input: VariableFeatureSetInput!) {
  updateVariableFeatureSet(id: $id, input: $input){
    ... VariableFeatureSetData
  }
}
