#import './ProductBasicFragment.gql'
#import './ProductPriceFragment.gql'
#import './ProductDeliveryFragment.gql'
#import './ProductVariableFeaturesFragment.gql'
#import './ProductVariationItemFragment.gql'
#import './ProductBrandFragment.gql'

fragment ProductData on Product{
  ... ProductBasicData

  ... ProductPriceData

  ... ProductBrandData

  ... ProductDeliveryData

  ... on VariableProduct {

    variableFeatures{
      ... ProductVariableFeatureData
    }

    variations{
      ... ProductVariationItemData
    }
  }
}
