fragment ProductVariationItemData on PVItem{
  id
  createdAt
  updatedAt
  sku
  published
  excerpt
  description
  technicalInformation
  price
  salePrice
  regularPrice
  volumePrice
  saleVolumePrice
  regularVolumePrice
  saleIsActive
  saleStartDate
  saleEndDate
  stock

  image

  sizeWidth
  sizeHeight
  sizeLength
  sizeUnit

  weightNet
  weightGross
  weightUnit

  packaging

  featuresConfig
}
