fragment ProductDeliveryData on Product{
  sizeWidth
  sizeHeight
  sizeLength
  sizeUnit

  weightNet
  weightGross
  weightUnit

  packageWidth
  packageHeight
  packageLength
  packageSizeUnit

  packageWeight
  packageWeightUnit

  packaging
}
