fragment ProductPriceData on Product{
      price
      salePrice
      regularPrice
      vat
      volumePrice
      saleVolumePrice
      regularVolumePrice
      saleIsActive
      saleStartDate
      saleEndDate
      saleType
      stock
}
